language: php
php:
    - 7.2
    - nightly
before_script:
  - export PATH=~/.composer/vendor/bin:$PATH
  - composer global require infection/infection
  - composer install
script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then infection -s --only-covered --min-msi=95; fi
after_script:
    - if [ "$TRAVIS_PHP_VERSION" != "nighlty" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" != "nighlty" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
