imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    secret:          "%secret%"
    serializer: ~
    default_locale:  "%locale%"
    php_errors:
        log: true

innmind_rest_client:
    content_type:
        json:
            priority: 0
            media_types:
                application/json: 0

old_sound_rabbit_mq:
    connections:
        default:
            host: '%rabbitmq_host%'
            port: '%rabbitmq_port%'
            user: '%rabbitmq_user%'
            password: '%rabbitmq_password%'
            vhost: '%rabbitmq_vhost%'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

            keepalive: true
            heartbeat: 60
            use_socket: true
    producers:
        crawl:
            connection:       default
            exchange_options: {name: 'crawl', type: direct}
