imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    secret:          "%secret%"
    serializer: ~
    default_locale:  "%locale%"
    php_errors:
        log: true

innmind_rest_client:
    content_type:
        json:
            priority: 0
            media_types:
                application/json: 0

innmind_homeostasis:
    actuator: homeostasis.actuator.provision_consumers

innmind_amqp:
    server:
        host: '%amqp_host%'
        port: '%amqp_port%'
        user: '%amqp_user%'
        password: '%amqp_password%'
        vhost: '%amqp_vhost%'
    exchanges:
        urls:
            type: direct
    queues:
        crawler:
            consumer: crawl_consumer
    bindings:
        -
            exchange: urls
            queue: crawler
