imports:
    - { resource: 'services/crawler.yml' }
    - { resource: 'services/html.yml' }
    - { resource: 'services/robots.yml' }

services:
   clock:
      class: Innmind\TimeContinuum\TimeContinuum\Earth
      arguments:
         - '@clock.timezone.paris'

   clock.timezone.paris:
      class: Innmind\TimeContinuum\Timezone\Earth\Europe\Paris
      public: false

   url_resolver:
      class: Innmind\UrlResolver\UrlResolver
