imports:
    - { resource: 'services/crawler.yml' }
    - { resource: 'services/html.yml' }
    - { resource: 'services/robots.yml' }
    - { resource: 'services/publishers.yml' }
    - { resource: 'services/delayers.yml' }
    - { resource: 'services/tracers.yml' }

services:
    clock:
        class: Innmind\TimeContinuum\TimeContinuum\Earth
        arguments:
            - '@clock.timezone.paris'

    clock.timezone.paris:
        class: Innmind\TimeContinuum\Timezone\Earth\Europe\Paris
        public: false

    url_resolver:
        class: Innmind\UrlResolver\UrlResolver

    crawl_consumer:
        class: AppBundle\Consumer\CrawlConsumer
        public: false
        arguments:
            - '@crawler'
            - '@publisher'
            - '%user_agent%'
