services:
    listener.resource_build.alternates:
        class: CrawlerBundle\EventListener\ResourceBuild\AlternatesListener
        tags:
            - { name: kernel.event_subscriber }

    listener.resource_build.images:
        class: CrawlerBundle\EventListener\ResourceBuild\ImagesListener
        tags:
            - { name: kernel.event_subscriber }
