services:
    parser.alternate:
        class: Innmind\Crawler\Parser\AlternateParser
        public: false
        arguments:
            - @resolver
            - @dom_factory
        tags:
            - { name: parser }

    parser.anchor:
        class: Innmind\Crawler\Parser\AnchorParser
        public: false
        arguments:
            - @dom_factory
        tags:
            - { name: parser }

    parser.android:
        class: Innmind\Crawler\Parser\AndroidParser
        public: false
        arguments:
            - @dom_factory
        tags:
            - { name: parser }

    parser.author:
        class: Innmind\Crawler\Parser\AuthorParser
        public: false
        arguments:
            - @dom_factory
        tags:
            - { name: parser }

    parser.base:
        class: Innmind\Crawler\Parser\BaseParser
        public: false
        arguments:
            - @dom_factory
        tags:
            - { name: parser, priority: 80 }

    parser.cache:
        class: Innmind\Crawler\Parser\CacheParser
        public: false
        tags:
            - { name: parser }

    parser.canonical:
        class: Innmind\Crawler\Parser\CanonicalParser
        public: false
        arguments:
            - @resolver
            - @dom_factory
        tags:
            - { name: parser }

    parser.charset:
        class: Innmind\Crawler\Parser\CharsetParser
        public: false
        arguments:
            - @dom_factory
        tags:
            - { name: parser }

    parser.cite:
        class: Innmind\Crawler\Parser\CiteParser
        public: false
        arguments:
            - @dom_factory
        tags:
            - { name: parser }

    parser.content:
        class: Innmind\Crawler\Parser\ContentParser
        public: false
        arguments:
            - @dom_factory
        tags:
            - { name: parser, priority: 60 }

    parser.description:
        class: Innmind\Crawler\Parser\DescriptionParser
        public: false
        arguments:
            - @dom_factory
        tags:
            - { name: parser, priority: 50 }

    parser.image:
        class: Innmind\Crawler\Parser\ImageParser
        public: false
        tags:
            - { name: parser }

    parser.images:
        class: Innmind\Crawler\Parser\ImagesParser
        public: false
        arguments:
            - @resolver
            - @dom_factory
        tags:
            - { name: parser }

    parser.ios:
        class: Innmind\Crawler\Parser\IosParser
        public: false
        arguments:
            - @dom_factory
        tags:
            - { name: parser }

    parser.journal:
        class: Innmind\Crawler\Parser\JournalParser
        public: false
        arguments:
            - @dom_factory
        tags:
            - { name: parser }

    parser.language:
        class: Innmind\Crawler\Parser\LanguageParser
        public: false
        arguments:
            - @dom_factory
        tags:
            - { name: parser }

    parser.links:
        class: Innmind\Crawler\Parser\LinksParser
        public: false
        arguments:
            - @resolver
            - @dom_factory
        tags:
            - { name: parser }

    parser.rss:
        class: Innmind\Crawler\Parser\RssParser
        public: false
        arguments:
            - @resolver
            - @dom_factory
        tags:
            - { name: parser }

    parser.theme_color:
        class: Innmind\Crawler\Parser\ThemeColorParser
        public: false
        arguments:
            - @dom_factory
        tags:
            - { name: parser }

    parser.title:
        class: Innmind\Crawler\Parser\TitleParser
        public: false
        arguments:
            - @dom_factory
        tags:
            - { name: parser }

    parser.uri:
        class: Innmind\Crawler\Parser\UriParser
        public: false
        tags:
            - { name: parser, priority: 100 }
