services:
    html.reader: '@html.reader.cache'

    html.reader.default:
        class: Innmind\Html\Reader\Reader
        public: false
        arguments:
            - '@html.node_translator'

    html.reader.cache:
        class: Innmind\Xml\Reader\CacheReader
        public: false
        arguments:
            - '@html.reader.default'

    html.node_translator:
        class: Innmind\Xml\Translator\NodeTranslator
        public: false
        factory:
            - AppBundle\Factory\NodeTranslatorFactory
            - make
