services:
    linker: '@linker.referrer'

    linker.default:
        class: AppBundle\Linker\Linker
        public: false
        arguments:
            - '@innmind_rest_client'

    linker.referrer:
        class: AppBundle\Linker\ReferrerLinker
        public: false
        arguments:
            - '@linker.default'
